### ISSUE TITLE
Dependencies from private pypi causes traceback

### ISSUE THREAD

**Issue by jtiai** [zehengl/pip-check-updates#5]
If dependency exists only in private pypi version resolving causes traceback:

```python
Traceback (most recent call last):
  File "/venv/bin/pcu", line 8, in <module>
    sys.exit(run())
  File "/venv/lib/python3.8/site-packages/pip_check_updates/__main__.py", line 126, in run
    change = compare_versions(current_version, latest_version)
  File "/venv/lib/python3.8/site-packages/pip_check_updates/__init__.py", line 24, in compare_versions
    latest_versioning = latest_version.split(".")
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by zehengl** [comment]
Thanks for reporting. Yes, now it only checks pypi. I think we may look for `--index-url` or `--extra-index-url` to determine if a private index is indented to use.

By the way, do you want to submit a pr?

**Comment by zehengl** [comment]
@all-contributors please add @jtiai for bug
