### ISSUE TITLE
Support for comma separated multiple version requirements

### ISSUE THREAD

**Issue by radusuciu** [zehengl/pip-check-updates#79]
Hi, thanks for the great project -- really awesome tool!

I encountered an error because in my `pyproject.toml` I specify some dependency ranges using the [comma separated syntax](https://python-poetry.org/docs/dependency-specification/#multiple-requirements) which is supported by `poetry` as well as `pdm` and documented in [`PEP440`](https://peps.python.org/pep-0440/#version-specifiers). For example, this is a valid PDM `pyproject.toml`:

```toml
[project]
name = "test_pcu"
version="0.0.1"
dependencies = [
    "svglib>=1.5.0,<2.0.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
```

However, `pip-check-updates` fails to parse this, giving this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pcu", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip_check_updates/__main__.py", line 70, in run
    deps = load_dependencies(req_path, not no_recursive, extra)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip_check_updates/parser.py", line 167, in load_dependencies
    load_toml(deps, f, p, pyproject=True, extras=extras)
  File "/usr/local/lib/python3.11/site-packages/pip_check_updates/parser.py", line 111, in load_toml
    packages = parse_requirements_lines(config.get(package_key, []))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip_check_updates/parser.py", line 101, in parse_requirements_lines
    requirements = [
                   ^
  File "/usr/local/lib/python3.11/site-packages/pip_check_updates/parser.py", line 102, in <listcomp>
    get_current_version(clean_requirements_line(requirement_line))
  File "/usr/local/lib/python3.11/site-packages/pip_check_updates/version.py", line 52, in get_current_version
    name, current_version = split_line
    ^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

**Comment by zehengl** [comment]
@all-contributors please add @radusuciu for bug

**Comment by radusuciu** [comment]
Workaround in the meantime: specify dependencies with `~=` instead.
